name = "wordle-royale"
type = "javascript"
compatibility_date = "2022-03-30"
account_id = "2dcc5a4f486a50625b4167e90d113158"
workers_dev = true
route = ""
zone_id = "" 

# [secrets]
# GEOCODE_API_KEY

kv_namespaces = [
  { binding = "GameManagerKV", id = "615337a9ebe748d6846bc84e6ac8895c" },
  { binding = "ShortUrlKV", id = "aaec78979d9b479abb62320bef056c96" }
]


[durable_objects]
bindings = [
  { name = "GameManager", class_name = "GameManagerDO" },
  { name = "RealTimeService", class_name = "RTMDO" }
]

[[migrations]]
tag = "v18" # Should be unique for each entry
deleted_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v19" # Should be unique for each entry
new_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v20" # Should be unique for each entry
deleted_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v21" # Should be unique for each entry
new_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v22" # Should be unique for each entry
deleted_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v23" # Should be unique for each entry
new_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v24" # Should be unique for each entry
deleted_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v25" # Should be unique for each entry
new_classes = ["GameManagerDO", "RTMDO"]

[[migrations]]
tag = "v26" # Should be unique for each entry
deleted_classes = ["GameManagerDO", "RTMDO"]


[[migrations]]
tag = "v27" # Should be unique for each entry
new_classes = ["GameManagerDO", "RTMDO"]

[miniflare]
kv_persist = true # Defaults to ./.mf/kv

[build]
command = "npm run build"
[build.upload]
format = "modules"
main='index.js'